// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANDKF_7E5nHI4a9HR5KBWilCaOFosanRA',
    appId: '1:47146965244:web:3e79b853db3ed626cedf79',
    messagingSenderId: '47146965244',
    projectId: 'flutter-booking-app-8eeb4',
    authDomain: 'flutter-booking-app-8eeb4.firebaseapp.com',
    storageBucket: 'flutter-booking-app-8eeb4.firebasestorage.app',
    measurementId: 'G-4B0HR2NZ6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sgmHIbTd8dPTqjZvVPoDETK3TliGr70',
    appId: '1:47146965244:android:2522c1a5d115ffd4cedf79',
    messagingSenderId: '47146965244',
    projectId: 'flutter-booking-app-8eeb4',
    storageBucket: 'flutter-booking-app-8eeb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllNdRyrlvguNQxkVqMIo7GKU9qXQVwTo',
    appId: '1:47146965244:ios:796b90b44e319ba4cedf79',
    messagingSenderId: '47146965244',
    projectId: 'flutter-booking-app-8eeb4',
    storageBucket: 'flutter-booking-app-8eeb4.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjecttBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDllNdRyrlvguNQxkVqMIo7GKU9qXQVwTo',
    appId: '1:47146965244:ios:796b90b44e319ba4cedf79',
    messagingSenderId: '47146965244',
    projectId: 'flutter-booking-app-8eeb4',
    storageBucket: 'flutter-booking-app-8eeb4.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjecttBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANDKF_7E5nHI4a9HR5KBWilCaOFosanRA',
    appId: '1:47146965244:web:d9cc8df7fdabc08ecedf79',
    messagingSenderId: '47146965244',
    projectId: 'flutter-booking-app-8eeb4',
    authDomain: 'flutter-booking-app-8eeb4.firebaseapp.com',
    storageBucket: 'flutter-booking-app-8eeb4.firebasestorage.app',
    measurementId: 'G-F497PN9L6Z',
  );

}